name: publish-to-pypi
description: Publish a project to pypi.org

inputs:
  project-name:
    description: The project name, which by convention is also the name of the folder at the root.
    required: true
  pypi-token:
    description: The pypi token to use for authentication
    required: true
  pre-release:
    description: Set to true if a pre-release version should be published.
    required: false
    default: false
  dry-run:
    description: Set to true for a test run that doesn't publish or tag.
    default: false

runs:
  using: 'composite'
  steps:
    - name: Setup/upgrade the python tools
      shell: bash
      run: python -m pip install --upgrade pip wheel setuptools poetry==1.1.8 coveo-pypi-cli==2.0.3 --user

    - name: Determine the minimum version for this release (the one in the pyproject.toml file)
      shell: bash
      id: get-minimum-version
      working-directory: ${{ inputs.project-name }}
      run: echo "::set-output name=minimum-version::$(${{ github.action_path }}/get-minimum-version.sh)"

    - name: Compute the release and prerelease versions
      id: get-versions
      shell: bash
      run: |
        RELEASE="$(python -m pypi next-version ${{ inputs.project-name }} --minimum-version ${{ steps.get-minimum-version.outputs.minimum-version }})"
        PRERELEASE="$(python -m pypi next-version ${{ inputs.project-name }} --prerelease --minimum-version ${{ steps.get-minimum-version.outputs.minimum-version }})"
        echo "::set-output name=release::$RELEASE"
        echo "Next release: $RELEASE"
        echo "::set-output name=prerelease::$PRERELEASE"
        echo "Next prerelease: $PRERELEASE"

    - name: Determine the version to publish.
      shell: bash
      id: get-next-version
      run: |
        if [[ ${{ inputs.pre-release }} == true ]]; then
          echo "::set-output name=version::${{ steps.get-versions.outputs.prerelease }}"
        else
          echo "::set-output name=version::${{ steps.get-versions.outputs.release }}"
        fi

    - name: Setup poetry for publish
      shell: bash
      working-directory: ${{ inputs.project-name }}
      run: |
        python -m poetry version ${{ steps.get-next-version.outputs.version }}
        python -m poetry build
        python -m poetry config pypi-token.pypi ${{ inputs.pypi-token }}

    - name: Publish to pypi.org
      shell: bash
      working-directory: ${{ inputs.project-name }}
      run: |
        if [[ ${{ inputs.dry-run }} == false ]]; then
          python -m poetry publish --no-interaction
        else
          echo "Just a dry run; we're not actually publishing"
        fi

#    - name: Tag repository
#      shell: bash
#      id: get-next-tag
#      run: |
#        TAG_NAME=${{ inputs.project-name }}.${{ steps.get-next-version.outputs.version }}
#        echo "::set-output name=tag-name::$TAG_NAME"
#        echo "This release will be tagged as $TAG_NAME"
#        git config user.name "github-actions"
#        git config user.email "actions@users.noreply.github.com"
#        git tag --annotate --message="Automated tagging system" $TAG_NAME ${{ github.sha }}
#
#    - name: Push the tag
#      shell: bash
#      env:
#        TAG_NAME: ${{ steps.get-next-tag.outputs.tag-name }}
#      run: |
#        if [[ ${{ inputs.dry-run }} == false ]]; then
#          git push origin $TAG_NAME
#        else
#          echo "If this wasn't a dry run, I would push this new tag named $TAG_NAME"
#        fi
